# TCP, clean regime, beta_H 1.0
type: train
env_name: defiance-nr-rl-handover
trainable: PPO
iterations: 100
max_episode_steps: 100
checkpoint_path: null
rollout_fragment_length: null
sample_timeout: 1200.0
evaluation_num_env_runners: 0
evaluation_interval: 2
evaluation_duration: "1"
evaluation_sample_timeout: 600.0

training_params:
  minibatch_size: 128
  entropy_coeff: [[0, 0.025], [40000, 0.01]]
  kl_target: 0.01
  lr: [[0, 0.0005], [40000, 0.00005]]
  vf_loss_coeff: 1.0
  vf_clip_param: 10.0
  lambda_: 0.9
  gamma: 0.9

ns3_settings:
  parallel: "7"
  simDuration: "50"
  topology: triangle
  rlMode: "true"
  handoverAlgorithm: agent
  transportProtocol: tcp
  flowDirection: ul
  addInterferingUes: "0"
  aerialUeRatio: "1.0"
  interfererMobility: "static"
  stepTime: "400"
  obsStackFrames: "2"
  rlAlphaGoodput: "0.8"
  rlBetaGoodput: "5"
  rlBetaHandover: "1.0"
  rlRewardComposition: multiplicative
  rlPingPongMultiplier: "5"
  rlHandoverHangoverLength: "1"
  rlRewardRefMbps: "35"
  rlRewardGoodputShape: "compl_pwr"
  rlRewardGoodputP: "0.4"
  bandwidthMhz: "30"
  numerology: "1"
  trafficRateMbps: "100"
  errorModel: "eesm-ir-t1"
  channelUpdateMs: "20"
  logging: "false"
