name: Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NS3_HOME: ns-3

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/defiance-project/bake-defiance:full-latest
      env:
        NS3_HOME: ${{ env.NS3_HOME }}

    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - name: Activate repository
        run: ln -s /code/ns-3 .

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.NS3_HOME }}/contrib/defiance
          clean: false

      - name: Build documentation
        working-directory: ${{ env.NS3_HOME }}/contrib/defiance/doc
        run: |
          mkdir -p $GITHUB_WORKSPACE/html
          doxygen doxygen.conf
          mv ./doc/html $GITHUB_WORKSPACE/html/doxygen
          make html
          mv build/html/* $GITHUB_WORKSPACE/html
          make latexpdf
          mv build/latex/*.pdf $GITHUB_WORKSPACE/html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: html

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
